gforge/cronjobs/followingnews.php
=> * News Notification

gforge/cronjobs/followingnews.php, gforge/plugins/mypage/www/index.php, gforge/plugins/simtk_news/www/simtk_news_utils.php
* add parameter for including or not includings news shown on project
homepage.
* fixed broken project link in news notification.
=> News Notification

gforge/cronjobs/followingnews.php
* Update footer text which is included in news notification cron job.
=> Footer change

gforge/common/include/Group.class.php, gforge/www/category/category.js, gforge/www/category/category.php, gforge/www/category/category_utils.php, gforge/www/category/communityPage.php, gforge/www/include/forum_db_utils.php, gforge/www/news/news_utils.php, gforge/www/project/admin/projCommunities.php
- Updated community page UI.
- Added support for adding project to community.
- Send email to community administrators for new pending request for approval.
Fixed:
https://simtk.org/tracker/?func=detail&atid=1960&aid=2480&group_id=11
=> Community page updates.

gforge/www/simulations/requestedJob.php, gforge/www/simulations/submitJob.php, gforge/www/simulations/viewJobs.php
- Displayed feedback message after job launch.
- Updated config text display font color.
- Updated message above config text.
=> Simulations UI updates.

gforge/www/frs/.htaccess, gforge/www/frs/download_start.php
- Increased from default execution time of 30sec to 60sec to allow time
of zip regeneration when needed.
- Added more path checking.
=> Downloads.

gforge/common/include/Group.class.php
- Updated email notification message.
=> Community page.

gforge/www/include/footer.php
* Change version to V2.0.9 in footer
=> New Version

gforge/www/simulations/requestedJob.php, gforge/www/simulations/util_simulations.php, gforge/www/simulations/viewJobs.php
- Moved recording and reserving remote server to earlier.
- Added more verbose message when permission is not given.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2492&group_id=11&atid=1960
=> Simulations.

gforge/www/githubAccess/admin/index.php, gforge/www/githubAccess/githubUtils.php, gforge/www/githubAccess/index.php
- Updated GitHub Access UI.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2481&group_id=11&atid=1960
=> GitHub Access.

gforge/common/frs/FRSFile.class.php, gforge/www/frs/admin/addfile.php, gforge/www/frs/admin/editfile.php, gforge/www/githubAccess/admin/index.php
- Updated checking in GitHub access URL setup in administration.
- Updated display name checking for GitHub downloads.
- Updated display name messages for GitHub downloads.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2494&group_id=11&atid=1960
=> Downloads: GitHub archive

gforge/www/category/ajax_categories.php, gforge/www/search/search.php, gforge/www/themes/simtk/Theme.class.php
- Fixed members lookup in categories/communities.
- Fixed typeSearch init.
- Increased default display of communities to 4.
=> Search and communities.

gforge/www/category/ajax_categories.php
- Should use short_description to get project description.
=> Search: project description.

gforge/common/reporting/Report.class.php, gforge/common/reporting/ReportSetup.class.php, gforge/common/reporting/report_utils.php, gforge/cronjobs/mail/mailing_lists_create.php
Fixes to daily downloads and page views.
https://simtk.org/tracker/index.php?func=detail&aid=2486&group_id=11&atid=1960
https://simtk.org/tracker/index.php?func=detail&aid=2502&group_id=11&atid=1960
=> Fixes to statistics/reports

gforge/www/include/footer.php, gforge/www/themes/simtk/Theme.class.php
update footer and Theme to v2.0.12.
=> verson change

gforge/cronjobs/genRecommend.py, gforge/cronjobs/genRecommend.sh, gforge/cronjobs/getActivity.php, gforge/cronjobs/getKeywords.php, gforge/cronjobs/getOntology.php, gforge/cronjobs/recommend_head.txt
- Migrated recommended projects cronjob.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2514&group_id=11&atid=1960
=> Recommended projects.

gforge/common/reporting/Report.class.php, gforge/common/reporting/ReportSetup.class.php, gforge/www/include/footer.php, gforge/www/themes/simtk/Theme.class.php
* Weekly and Monthly Download fix
https://simtk.org/tracker/index.php?func=detail&aid=2497&group_id=11&atid=1960
=> Reporting fixes

gforge/www/include/user_home.php, phpBB3/searchPhpbb.php
- Displays search results in an iframe.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2277&group_id=11&atid=1960
=> Downloads: users forum post history.

gforge/www/include/login-form.php
- Updated message on the log in screen to be more user-friendly.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2324&group_id=11&atid=1960
=> Log in screen message.

gforge/www/account/change_email.php, gforge/www/account/register.php
Added warning about not to use hotmail account.
=> Registration: hotmail account.

gforge/www/include/header.php
- Fixed header for login screen to include project and people search.
=> Header for login screen.

gforge/www/simulations/util_simulations.php, gforge/www/simulations/viewSubmittedJobs.php
- Decoupled Postgresql and SSL operations with cronjob to avoid
interference.
- Added database results validity checking.
- Moved recordRemoteServerJobStart().
- Improved db query for project and user names.
- Moved email send.
- Cleaned up ssh and sftp with disconnect() after usage.
=> Fixed PHP Postgresql/SSL interference problem.

gforge/www/include/footer.php, gforge/www/themes/simtk/Theme.class.php
=> Footers for v2.0.14

gforge/www/themes/simtk/Theme.class.php
- Used abbrGroupName() from utils.php, that had been updated, for
communities abbreviation, rather than having 2 copies of abbreviation.
=> V2.0.15. Shared abbreviation.

phpBB3/viewforum.php
- Reversed viewforum.php back to the default phpBB installation version.
- The capability of this file is needed in order to support “Follow
forum” and “Unfollow”. Cannot redirect to indexPhpbb.php.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2567&group_id=11&atid=1960
=> Forum: Follow/Unfollow.

gforge/cronjobs/rotate_activity.php, gforge/www/include/login-form.php, gforge/www/simulations/cancelJob.php, gforge/www/simulations/getModelsInfo.php, gforge/www/simulations/getServersInfo.php, gforge/www/simulations/launchJob.php, gforge/www/simulations/requestedJob.php, gforge/www/simulations/submitJob.php, gforge/www/simulations/util_simulations.php, gforge/www/simulations/util_submitted_jobs.php, gforge/www/simulations/viewJobs.php
- Updated message in log-in page.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2570&group_id=11&atid=1960
=> Log-in page.

gforge/cronjobs/getProjectForumStats.sql
- Updated with checking for topic_visibility and post_visibility to
account for soft-deletion
=> Cronjob forum statistics.

gforge/www/feedback.php, gforge/www/include/footer.php, gforge/www/sendmessage.php, gforge/www/themes/simtk/Theme.class.php
- Updated Contact and Feedback pages for contacting webmaster and
project admins.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2562&group_id=11&atid=1960
=> Contact/Feedback pages.

gforge/www/include/footer.php, gforge/www/themes/simtk/Theme.class.php, phpBB3/indexPhpbb.php, phpBB3/postingPhpbb.php, phpBB3/viewtopicPhpbb.php
- Release V2.0.19
- Added link in Forums page to forum statistics.
Fixed:
https://simtk.org/tracker/?func=detail&atid=1960&aid=2575&group_id=11
=> Forum Statistics.

gforge/cronjobs/mail/mailaliases.php
- Do not unset the tracker or forum entries.
=> email aliases generation.

gforge/www/include/footer.php, gforge/www/themes/simtk/Theme.class.php
=> Release v2.0.24

phpBB322/appPhpbb.php, phpBB322/indexPhpbb.php, phpBB322/postingPhpbb.php, phpBB322/searchPhpbb.php, phpBB322/viewtopicPhpbb.php
- Prepend proper path for iframeAdjust.js.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2670&group_id=11&atid=1960
=> Forum topic tags search.

gforge/plugins/datashare/www/view.php, gforge/www/include/footer.php, gforge/www/themes/simtk/Theme.class.php
* Change version number
* Remove reference to server name
=> Files changes for new release

gforge/plugins/following/www/followers.css
- Updated CSS to fix problem with Google map controls.
=> Google map controls.

gforge/cronjobs/utilsGitHubSave.php
- Fixed path for GitHub access.
=> GitHub cronjob

gforge/plugins/datashare/www/view.php, gforge/www/include/footer.php, gforge/www/themes/simtk/Theme.class.php
* send firstname and lastname to datashare session.
=> changes to datashare

gforge/common/frs/include/frs_utils.php, gforge/www/frs/download_start.php
- Added warning message and email to SimTK webmaster if file to be downloaded is missing.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2839&group_id=11&atid=1960
=> Downloads: missing file handling.

installation/fusionforgeInstall.txt
- Included uuid-runtime in installed packages.
=> Installation.

gforge/www/include/footer.php, gforge/www/themes/simtk/Theme.class.php
=> Release v3.0.5.

gforge/www/frs/admin/construct_admin_ui.php, gforge/www/frs/construct_ui.php
- Updated bootstrap popover invocation.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2846&group_id=11&atid=1960
=> Downloads: License.

gforge/plugins/reports/www/index.php, gforge/www/include/popupmenuSetup.php, gforge/www/project/admin/statistics.php
- Checked whether downloads is enabled before showing report.
Fixed:
https://simtk.org/tracker/?func=detail&atid=1960&aid=2852&group_id=11
=> Report: downloads.

gforge/www/include/header.php
- Updated header in login page.
Fixed:
https://simtk.org/tracker/?func=detail&atid=1960&aid=2860&group_id=11
=> Login header.

fusionforge/common/include/Group.class.php, fusionforge/common/include/logger.php, fusionforge/plugins/datashare/include/Datashare.class.php
- Updated subject line in email messages for project and Datashare study submission requests.
- Added variables validity check to logger.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=3011&group_id=11&atid=1960
=> Email messages for project and DataShare study submission.

fusionforge/common/include/Group.class.php
- Updated subject line and message for project approval.
Fixed:
https://simtk.org/tracker/?func=detail&atid=1960&aid=3011&group_id=11
=> Project submission email.

fusionforge/plugins/datashare/www/admin/add.php, fusionforge/plugins/datashare/www/admin/edit.php
- Updated toolip for license agreement.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2953&group_id=11&atid=1960
=> [datashare] License.

fusionforge/common/include/utilsGitHubSave.php
- Updated notification message when GitHub archive upload fails per feedback.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2966&group_id=11&atid=1960
=> [Downloads] GitHub archive upload.

fusionforge/www/frs/admin/obtainPackageDoi.php
- Updated text. Added indentation.
Fixed:
https://simtk.org/tracker/?func=detail&atid=1960&aid=2970&group_id=11
=> [downloads] Updated DOI warning message.

fusionforge/plugins/datashare/www/admin/cancelStudyDoi.php, fusionforge/plugins/datashare/www/admin/index.php, fusionforge/www/frs/admin/index.php, fusionforge/www/frs/admin/obtainPackageDoi.php, fusionforge/www/themes/simtk/Theme.class.php
- Updated DOI assignment and cancellation pages.
- Updated DOI text on DataShare admin page.
Fixed:
https://simtk.org/tracker/?func=detail&atid=1960&aid=3021&group_id=11
=> [downloads, datashare] Text and formatting changes.

fusionforge/cronjobs/db/rotate_activity.php, fusionforge/www/include/footer.php, fusionforge/www/themes/simtk/Theme.class.php
- Release v4.1.0.
- Increased activity logs.
- Increased communities.
=> Release v4.1.0.

fusionforge/www/aboutCommunities.php, fusionforge/www/themes/simtk/Theme.class.php
- Added a link to the Communities drop-down for “About Communities.”
This goes to a page that says: "Communities are collections of
projects that automatically display the latest news, publications,
and discussions happening among those projects."
There are two buttons:
Explore communities - goes to the communities page.
Request a community – goes to the community request page.
- Added a second link the Communities drop-down for "Request Community".
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=3026&group_id=11&atid=1960
=> [Communities] Added Community Request page.

fusionforge/common/include/account.php, fusionforge/www/account/register.php, fusionforge/www/register/index.php
- Return more verbose from project identifier and account name checks.
- Updated hint on project identifier to include starting with alphanumeric character.
- Updated hint on account name to include starting with alphanumeric character.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=3036&group_id=11&atid=1960
https://simtk.org/tracker/index.php?func=detail&aid=3042&group_id=11&atid=1960
=> [project, account] Checks on project identifier and account name.

fusionforge/www/frs/admin/addfile.php, fusionforge/www/frs/admin/editfile.php, fusionforge/www/register/index.php, fusionforge/www/themes/simtk/Theme.class.php
- Updated checkbox text to "Collect user information for
download statistics (requires user login)".
- Removed tooltip for collect user information option.
- Updated section name to "Select Download File Options".
- Added a divider between the list and communities links in
Project->communities menu items.
- Updated restrictions for Short project identifier.
Fixed:
https://simtk.org/tracker/?func=detail&atid=1960&aid=3014&group_id=11
https://simtk.org/tracker/?func=detail&atid=1960&aid=3026&group_id=11
https://simtk.org/tracker/?func=detail&atid=1960&aid=3036&group_id=11
=> [Downloads, Communities, Project] Updated UI and messages.

fusionforge/www/frs/download_confirm.php, fusionforge/www/frs/download_start.php, fusionforge/www/frs/download_utils.php, fusionforge/www/frs/getDownloadStatus.php, fusionforge/www/frs/utilsDownloadProgress.js
- Added message for tracking file download progress.
- Added Return to Download button.
- Fixed adding to mailing list in file download.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2334&group_id=11&atid=1960
=> [Downloads] Feedback for file download.

fusionforge/www/frs/download_confirm.php, fusionforge/www/frs/download_utils.php
- Updated DIV for user inputs.
Fixed:
https://simtk.org/tracker/?func=detail&atid=1960&aid=2334&group_id=11
=> [Downlaods] Feedback for file download.

phpBB322/styles/prosilver/template/mcp_move.html
- Updated position of project selector.
=> [Forum] Forum moderator's page layout.

fusionforge/www/frs/utilsDownloadProgress.js
- Updated message shown when tracking download progress.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=2334&group_id=11&atid=1960
=> [Downloads] Feedback when file is downloaded

fusionforge/www/include/footer.php
=> Release 4.1.1

fusionforge/plugins/datashare/www/userLogin.php, fusionforge/plugins/datashare/www/view.php
- Added support for download of multiple files and directories as a zip file.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=3056&group_id=11&atid=1960
=> [data share] Multiple files and directories download.

fusionforge/plugins/datashare/www/userLogin.php
- Added support for download of multiple files and directories as a zip file.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=3056&group_id=11&atid=1960
=> [data share] Support multiple files and directories download.

fusionforge/common/include/account.php, fusionforge/cronjobs/db/createDataShareStudies.php, fusionforge/www/account/change_pw.php, fusionforge/www/account/lostlogin.php, fusionforge/www/account/newpw.php
- Updated user registration and server infrastructure.
=> User registration and server infrastructure.

fusionforge/www/include/footer.php, fusionforge/www/themes/simtk/Theme.class.php
=> Release v4.1.3.

fusionforge/www/frs/download_utils.php
- Corrected error of extra quote.
Fixed:
https://simtk.org/tracker/?func=detail&atid=1960&aid=3093&group_id=11
https://simtk.org/tracker/?func=detail&atid=1960&aid=3094&group_id=11
=> [Download] Download confirm page.

fusionforge/common/tracker/actions/tracker.php
=> [tracker] Extra fields.

fusionforge/www/include/footer.php, fusionforge/www/themes/simtk/Theme.class.php
=> Release v4.1.5.

fusionforge/common/include/user_profile.php, fusionforge/www/aboutCommunities.php, fusionforge/www/account/first.php, fusionforge/www/account/settings.php, fusionforge/www/category/communityAdmin.php, fusionforge/www/communities.php, fusionforge/www/feedback.php, fusionforge/www/include/header.php, fusionforge/www/include/user_home.php, fusionforge/www/project/admin/index.php, fusionforge/www/project/report/index.php, fusionforge/www/sendmessage.php, fusionforge/www/themes/simtk/Theme.class.php
- Enabled email send message and updated handling.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=3087&group_id=11&atid=4567
=> [Feedback] Email send message.

phpBB322/language/en/search.php
- Added copyright to phpBB search instructions file.
=> Copyright.

fusionforge/www/frs/genDatasetInfo.php
- Updated data for Google dataset indexing to show information when
either downlaod or datashare study is available.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=3022&group_id=11&atid=1960
=> [data share] Google dataset indexing.

fusionforge/www/include/user_home.php
- Added support for entry and display of ORCID for user account,
in user registration, edit profile, and view profile pages.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=3099&group_id=11&atid=1960
=> [account] Support for ORCID.

fusionforge/www/include/user_home.php
- Updated per feedback.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=3099&group_id=11&atid=1960
=> [account] Support for ORCID ID.

fusionforge/www/project/memberlist.php
- Added check for member list.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=3102&group_id=11&atid=1960
=> [project] Empty member list.

fusionforge/www/frs/admin/construct_admin_ui.php, fusionforge/www/frs/admin/editfile.php, fusionforge/www/frs/construct_ui.php, fusionforge/www/include/trove.php
- Updated handling of release time for file upload.
- Validate array element before usage for trove.
https://simtk.org/tracker/index.php?func=detail&aid=3112&group_id=11&atid=1960
=> [downloads] Display of last updated date for file upload.

fusionforge/www/include/popupmenuSetup.php, fusionforge/www/include/project_home.php, fusionforge/www/project/admin/addFunder.php, fusionforge/www/project/admin/deleteFunder.php, fusionforge/www/project/admin/layout.php, fusionforge/www/project/admin/manageFunders.php, fusionforge/www/project/admin/updateFunder.php, fusionforge/www/project/funderinfo.php, fusionforge/www/themes/simtk/Theme.class.php
-- added manageFunders.php (admin)
-- Added update, add and delete operations for funders -- added added links to popupmenus about and admin -- added checkbox to main project layout for showing funder information on project summary
-- added logic to display funder info on project summary -- added small changes to Theme.class.php, popupmemenuSetup.php,
=> [Project] Added the ability manage funder information for projects.

fusionforge/www/include/project_home.php, fusionforge/www/project/admin/addFunder.php, fusionforge/www/project/admin/updateFunder.php, fusionforge/www/project/funderinfo.php, fusionforge/www/themes/simtk/Theme.class.php
-- updated some text on forms
-- updated text on funder info screens
=> [Project] Funder Information -  Simple UI Fixes.

fusionforge/www/faq.php
- Updated About->FAQ to include question and answer on private project access.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=3225&group_id=11&atid=1960
=> [FAQ] Update to include Q&A on private project.

fusionforge/www/project/admin/layout.php
-- adding a link to manage funders on the main page layout screen to
=> [Project] Funder Information - Fixed missing link

fusionforge/www/include/project_home.php, fusionforge/www/project/admin/addFunder.php, fusionforge/www/project/admin/manageFunders.php, fusionforge/www/project/admin/updateFunder.php
-- on project home, funder info is moved above the news section. -- award number is no longer required
-- displaying of funder info on manage funders was update do
remove a trailing comma
=> [Porject] Funder Information UI Changes

fusionforge/www/include/footer.php, fusionforge/www/themes/simtk/Theme.class.php
=> Release 4.2.1.

fusionforge/www/project/admin/manageFunders.php
- Fixed funders admin page when page is empty.
=> Funders admin page

fusionforge/plugins/datashare/www/admin/add.php, fusionforge/plugins/datashare/www/admin/edit.php
- Updated link for Data Share->Administration->Add Study/Edit to point to metadata_DirectoryTemplate.php
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=3245&group_id=11&atid=1960
=> [datashare] Updated link to metadata documentation.

fusionforge/www/include/popupmenuSetup.php
-- If display funder information is set to no, hide the Funder Information link in the about drop down.
=> [Funder Information] Hiding Funder Info link

fusionforge/www/themes/simtk/css/theme.css
- Updated css to fix alignment.
Fixed:
https://simtk.org/tracker/index.php?func=detail&aid=3241&group_id=11&atid=1960
=> [Project] Home page alignment.

fusionforge/www/project/admin/index.php, fusionforge/www/register/index.php
-- Summarys for projects can now only have 286 or fewer characters.
=> [Project Summary] Adding enforcement of summary length
